# Generated by Django 4.1.1 on 2022-11-15 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=200, null=True)),
                ("second_name", models.CharField(max_length=200, null=True)),
                ("third_name", models.CharField(max_length=200, null=True)),
                ("reg_number", models.CharField(max_length=200, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("LOST", "Lost"), ("FOUND", "Found")],
                        default="FOUND",
                        max_length=200,
                    ),
                ),
                ("id_number", models.CharField(max_length=200, null=True)),
                ("school_name", models.CharField(max_length=200, null=True)),
                ("department", models.CharField(max_length=200, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("location_found", models.CharField(max_length=200, null=True)),
            ],
            options={
                "verbose_name": "Card",
                "verbose_name_plural": "Cards",
            },
        ),
    ]
