# Generated by Django 4.1.1 on 2022-11-15 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="first_name",
            new_name="college_name",
        ),
        migrations.RenameField(
            model_name="card",
            old_name="id_number",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="card",
            name="school_name",
        ),
        migrations.RemoveField(
            model_name="card",
            name="second_name",
        ),
        migrations.RemoveField(
            model_name="card",
            name="third_name",
        ),
        migrations.AddField(
            model_name="card",
            name="id_string",
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="location_found",
            field=models.CharField(
                choices=[
                    ("A", "GATE_A"),
                    ("B", "GATE_B"),
                    ("C", "GATE_C"),
                    ("D", "GATE_D"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="status",
            field=models.CharField(
                choices=[
                    ("L", "LOST"),
                    ("C", "CLAIMED"),
                    ("F", "FOUND"),
                    ("R", "REGISTERED"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
