# Generated by Django 4.1.1 on 2022-11-02 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="status",
            field=models.CharField(
                choices=[("LOST", "Lost"), ("FOUND", "Found")],
                default="FOUND",
                max_length=200,
            ),
        ),
    ]
