# Generated by Django 4.1.1 on 2022-11-16 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_rename_first_name_card_college_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="college_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="department",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="id_string",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="location_found",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "GATE_A"),
                    ("B", "GATE_B"),
                    ("C", "GATE_C"),
                    ("D", "GATE_D"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="reg_number",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="card",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("L", "LOST"),
                    ("C", "CLAIMED"),
                    ("F", "FOUND"),
                    ("R", "REGISTERED"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
