# Generated by Django 4.1.1 on 2022-11-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_card_location_found"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="names",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="card",
            name="second_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="third_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
